---
- hosts: ceph-nodes 
  gather_facts: false
  become: true
  tasks:
    - name: Add specified Repo into sources.list
      apt_repository:
        repo: deb [arch=amd64 trusted=yes] http://x.x.x.x:x/rhcs3.3/{{item}} xenial main
        state: present
      with_items:
      -  MON
      +
      -  OSD
      -  Tools

    - name: update repos cache and install "ceph-common" package
      apt:
        update_cache: yes

