---
- name: install ceph-mon and ceph-mgr packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ceph-mon
    - ceph-mgr
  when: mighost == ansible_hostname

- name: update ceph.conf | set fact monhost base
  set_fact: 
    monhost: ""
  changed_when: 1 == 2

- name: update ceph.conf | populate fact monhost
  set_fact: 
    monhost: "{{ monhost }}{{ ansible_hostname }},"
  with_items:
    - "{{ groups['mons'] }}"
  changed_when: 1 == 2

- name: update ceph.conf | add to from ceph.conf
  lineinfile:
    path: "/etc/ceph/ceph.conf"
    regexp: '^mon initial members = '
    line: "mon initial members = {{ monhost[:-1] }}"
  when: ansible_hostname != mighost

- name: update ceph.conf | set fact monip base
  set_fact: 
    monip: ""
  changed_when: 1 == 2

- name: update ceph.conf | populate fact monip
  set_fact: 
    monip: "{{ monip }}{{ hostvars[item]['ansible_eth1'].ipv4.address }},"
  with_items:
    - "{{ groups['mons'] }}"
  changed_when: 1 == 2

- name: fetch ceph.conf from mon cluster memeber node
  fetch:
    src: "/etc/ceph/ceph.conf"
    dest: "../backup/"
    flat: yes
  when: ansible_hostname != mighost

- name: copy ceph.conf to new mon node {{ mighost }}
  copy:
    src: "roles/spinner/files/ceph.conf"
    dest: "/etc/ceph/"
    owner: ceph
    group: ceph
  when: mighost == ansible_hostname

- name: create default directory on {{ mighost }}
  file:
    path: "/var/lib/ceph/mon/{{ clustername }}-{{ ansible_hostname }}"
    state: directory
  when: mighost == ansible_hostname

- name: create temp directory on "{{ mighost }}"
  file:
    path: "/tmp/ceph"
    state: directory
  when: mighost == ansible_hostname

- name: fetch keyring from mon cluster memeber node
  fetch:
    src: "/etc/ceph/{{ clustername }}.client.admin.keyring"
    dest: "roles/spinner/files/"
    flat: yes
  when: ansible_hostname != mighost

- name: copy keyring to new mon node {{ mighost }}
  copy:
    src: "roles/spinner/files/{{ clustername }}.client.admin.keyring"
    dest: "/etc/ceph/"
    owner: ceph
    group: ceph
  when: mighost == ansible_hostname

- name: retrieve the monitor keyring
  shell: "ceph auth get mon. -o /tmp/ceph/monkeyfile" 
  when: mighost == ansible_hostname

- name: retrieve the monitor mapfile
  shell: "ceph mon getmap -o /tmp/ceph/monmapfile"
  when: mighost == ansible_hostname

- name: prepare monitor {{ mighost }} data directory
  shell: "ceph-mon -i {{ mighost }} --mkfs --monmap /tmp/ceph/monmapfile --keyring /tmp/ceph/monkeyfile"
  when: mighost == ansible_hostname

- name: update permissions on mon dir
  file:
    path: "{{ item }}"
    owner: ceph
    group: ceph
    recurse: yes
    state: directory
  when: mighost == ansible_hostname
  with_items:
    - "/var/log/ceph"
    - "/var/run/ceph"
    - "/etc/ceph"
    - "/var/lib/ceph/mon"

- name: start ceph-mon process 
  service:
    name: "ceph-mon@{{ mighost }}"
    state: started
    enabled: yes 
  when: mighost == ansible_hostname

- name: check mgr dir exists
  file:
    path: "/var/lib/ceph/mgr/{{ clustername }}-{{ mighost }}"
    owner: ceph
    group: ceph
    state: directory
  when: mighost == ansible_hostname

- name: create authentication key for ceph-mgr daemon
  shell: "ceph auth get-or-create mgr.{{ mighost }} mon 'allow profile mgr' osd 'allow *' mds 'allow *'"
  register: mgrkey
  when: mighost == ansible_hostname

- name: create mgr keyfile
  file:
    path: "/var/lib/ceph/mgr/{{ clustername }}-{{ mighost }}/keyring"
    owner: ceph
    group: ceph
    state: touch
  when: mighost == ansible_hostname


- name: add key to keyfile
  lineinfile:
    path: "/var/lib/ceph/mgr/{{ clustername }}-{{ mighost }}/keyring"
    line: "{{mgrkey.stdout}}"
    owner: ceph
    group: ceph
  when: mighost == ansible_hostname
    
      
- name: start mgr daemon
  shell: "ceph-mgr -i {{ mighost }}"
  when: mighost == ansible_hostname
