---
 
- name: fetch keyring from mon cluster memeber node
  fetch:
    src: "/etc/ceph/{{ clustername }}.client.admin.keyring"
    dest: "roles/spinner/files/"
    flat: yes

- name: fetch ceph.conf from mon cluster memeber node
  fetch:
    src: "/etc/ceph/ceph.conf"
    dest: "roles/spinner/files/"
    flat: yes

- name: install ceph-osd package
  package:
    name: ceph-osd
    state: present
  when: mighost == ansible_hostname

- name: create default directory on {{ mighost }}
  file:
    path: "{{ item }}"
    owner: ceph
    group: ceph
    recurse: yes
    state: directory
  with_items:
    - "/etc/ceph"
    - "/var/lib/ceph/osd/"
    - "/var/log/ceph"
    - "/var/run/ceph"
  when: mighost == ansible_hostname 

- name: list osd mountpoints from backup
  shell: "cat roles/spinner/files/mountpoints"
  register: mountpoints
  delegate_to: localhost

- name: create osd directories
  file: 
    path: "{{ item }}"
    owner: ceph 
    group: ceph 
    recurse: yes 
    state: directory
  with_items: "{{ mountpoints.stdout_lines }}"

- name: copy keyring to new mon node {{ mighost }}
  copy:
    src: "roles/spinner/files/{{ clustername }}.client.admin.keyring"
    dest: "/etc/ceph/"
    owner: ceph
    group: ceph
  when: mighost == ansible_hostname

- name: copy ceph.conf to new mon node {{ mighost }}
  copy:
    src: "roles/spinner/files/ceph.conf"
    dest: "/etc/ceph/"
    owner: ceph
    group: ceph
  when: mighost == ansible_hostname

- name: sleep for 10 seconds and continue with play
  wait_for: timeout=10
  delegate_to: localhost

- name: check permissions on disks
  file:
    path: "/var/lib/ceph/osd/"
    owner: ceph
    group: ceph
    recurse: yes
    state: directory
  when: mighost == ansible_hostname

- name: sleep for 10 seconds and continue with play
  wait_for: timeout=10
  delegate_to: localhost

- name: check osds on {{ mighost }} are started
  shell: "ceph-volume lvm activate --all"
  when: mighost == ansible_hostname

- name: unfreeze osds in cluster
  shell:  "{{ item }}"
  with_items:
    - "ceph osd unset noout"
    - "ceph osd unset norecover"
    - "ceph osd unset norebalance"
    - "ceph osd unset noscrub"
    - "ceph osd unset nodeep-scrub"
    - "ceph osd unset nobackfill"
  delegate_to:  "{{ groups.mons | first }}"
  run_once: yes
